yv/urls.py
from django.contrib import admin
from django.urls import path
"""nkunzi URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('yvfoundation.urls')),
    path('yvfoundation/', include('yvfoundation.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yvfoundation/urls.py
from . import views
from .views import contact_view
from django.urls import path
from . models import *


app_name = "yvfoundation"

urlpatterns = [
    path('',views.yvfoundationhome,name='home'),
    path('contact/',contact_view,name="contact"),
    path('about/',views.AboutView.as_view(),name="about"),
    ]

yvfoundation/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse

TOPIC_CHOICES = (
 ('general', 'General enquiry'),
 ('suggestion', 'Suggestion')
)

class Contact(models.Model):
    topic = models.CharField(choices=TOPIC_CHOICES,max_length=40)
    message = models.CharField(max_length=200)
    sender = models.EmailField(null=True,blank=True)

    def __str__(self):
        return self.topic

yvfoundation/forms.py
from django import forms
from django.forms import ModelForm
from . models import Contact


TOPIC_CHOICES = (
 ('general', 'General enquiry'),
 ('suggestion', 'Suggestion')
)
class ContactForm(ModelForm):
    topic = forms.ChoiceField(choices=TOPIC_CHOICES,widget=forms.Select(attrs={'class': 'p-2 form-control caret'}))
    message = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "message", "rows": 4, "id":"message","cols": 25,"class":"p-2 form-control"}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={"placeholder": "Your Email (Optional)","id":"sender","class":"p-2 form-control"}),required=False)
    class Meta:
        model = Contact
        fields = "__all__"

yvfoundation/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.views.generic import FormView,TemplateView

from .models import Contact
from .forms import ContactForm

def yvfoundationhome(request):
    form = ContactForm()
    context = {"form": form}
    return render(request,"yvfoundation/index.html",context)

class AboutView(TemplateView):
    template_name = "yvfoundation/about.html"


# class ContactView(FormView):
#     template_name = 'yvfoundation/contact.html'
#
#     def get(self, request, *args, **kwargs):
#         form = ContactForm()
#         context = {"form": form}
#         return render(self.request, "yvfoundation/contact.html", context)
#
#     def post(self, request, *args, **kwargs):
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             topic = form.cleaned_data['topic']
#             message = form.cleaned_data['message']
#             sender = form.cleaned_data.get('sender', 'noreply@example.com')
#             form.save()
#             # send_mail(
#             #     'Feedback from your site, topic: %s' % topic,
#             #     message, sender,
#             #     ['molusi.abigail@gmail.com']
#             # )
#             form = ContactForm()
#             return redirect('yvfoundation:home')
#         else:
#             form.errors
# views.py



def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            topic = form.cleaned_data['topic']
            message = form.cleaned_data['message']
            sender = form.cleaned_data.get('sender')
            if not sender:
                sender="anonymous"
            send_mail(
                subject=f"topic:{topic}",
                message=f'New message: "{message}" sent by: {sender}',
                from_email='molusi.abigail@gmail.com',  # Change to your desired email sender
                recipient_list=['yvfoundation1@gmail.com'],  # Change to the recipient email
                fail_silently=False,
            )
            print("Got in==================================")
            return redirect('yvfoundation:home')
        else:
            form.errors
    else:
        form = ContactForm()
    context={"form":form}
    return render(request,"yvfoundation/contact.html", context)

templates/yvfoundation/about.html
{% extends 'yvfoundation/index.html' %} {% load static %} {% static "images" as baseUrl %}
{% block content %}


<div class="container" style="height:90%;display:flex;justify-content:center;flex-direction:column;align-items:center;margin-bottom:0;padding-bottom:100px">

      <div class="row " style="display:flex;justify-content:center;align-items:center;margin:8% auto">
        <div class="about-info py-0 my-0 col-md-6 col-sm-12"  >
            <p class="text-center ">
                <div class="row mb-5 mt-0">
        <h4 style="text-align:center;font-family:italic;font-family: 'Libre Baskerville', serif;"><span class="first-letter ">A</span>bout</h4>
        </div>
            <p>
                <b>YV Foundation</b> is a non-profit organization which was established in 2020 by a group of 4 young women aged
                “between” 23 to 34, who want to help with youth development and raise awareness around Gender Based Violence in mainly
                disadvantaged communities in South Africa. The organization addresses social issues such as unemployment and
                gender based violence.

            </p>

        </div>

      </div>
    <div class="col-md-4" style="align-items:center;display:flex;justify-content:space-around;flex-direction:row;margin: 0 auto">
<a href="{% url 'yvfoundation:home' %}" style="font-size:1.4rem;color:black;display:inline"><i class="fa-solid fa-house"></i></a>
              <a href="{% url 'yvfoundation:contact' %}" style="font-size:1.4rem;color:black;display:inline"> <i class="fa-solid fa-envelope"></i></a>
               <a href="{% url 'yvfoundation:contact' %}" style="font-size:1.6rem;color:blue;display:inline"><i class="fa-brands fa-facebook"></i></a>
    </div>

        </div>

{% endblock %}

templates/yvfoundation/contact.html
{% extends 'yvfoundation/index.html' %}
{% load static %}
{% static "images" as baseUrl %}
{% block content %}

<div class="container" id="container" style="width:100%;height:100%;padding:5rem;margin:auto;display:flex;flex-direction:column;justify-content:center;padding-bottom:250px">
<div class="container" style="margin:50px auto">
        <div class="row my-5">
        <h4 style="text-align:center;font-family: 'Libre Baskerville', serif;"><span class="first-letter ">C</span>ontact us</h4>
        </div>

       <div class="row contact-details" >
       <div class="contact-info col-md-6 col-sm-12 mt-5">
            <p>Ditsobotla,South Africa<br>
            073 3444 977<br>
            yvfoundation1@gmail.com
            </p>
       </div>
       <div class="col-md-6 col-sm-12" >
           <form class="my-form" action=".">
         {% csrf_token %}

               <p>{{ form.topic }}</p>
               <p>{{ form.message }}</p>
               <p>{{ form.sender }}</p>


                <button class="btn btn-primary btn-sm px-5" type="submit" id="sub-btn">submit</button>

            </form>
       </div>
       </div>

    </div>

    <div class="modalo p-0" >
    <div id="contents">
        <div class="closebar" style="display:flex;justify-content:flex-end;">
        <button class="close-btn btn ">X</button>
        </div>
    <h4 id="feedback"  class="pb-5">Thanks for your feedback.</h4>




</div>

    </div>
    <div class="col-md-4" style="align-items:center;display:flex;justify-content:space-around;flex-direction:row;margin: 0 auto">
               <a href="{% url 'yvfoundation:contact' %}" style="font-size:1.6rem;color:blue;display:inline"><i class="fa-brands fa-facebook"></i></a>
    </div>
    </div>

{% endblock %}

templates/yvfoundation/index.html
<!DOCTYPE html>
{% load static %}
{% static "images" as baseUrl %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>YV Foundation</title>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
      <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Angkor&family=Fjalla+One&family=Kaushan+Script&family=Lilita+One&family=Merienda&family=Permanent+Marker&family=Supermercado+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

<style>
    body{
    ::-webkit-scrollbar {
    width: 10px; /* Adjust the width as needed */
}

::-webkit-scrollbar-thumb {
    background-color: grey; /* Set the thumb color to white */
}

::-webkit-scrollbar-track {
    background-color: transparent; /* Set the track color to transparent or a color of your choice */
}
    scrollbar-color: white transparent;}
</style>

</head>
<body >
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark " style=" position: fixed;top: 0;width: 100%;z-index: 1000">
    <div class="container">
        <a class="navbar-brand" href="{% url 'yvfoundation:home' %}"><div class="m-0 p-0" id="main-logo"><h4 style="font-family:Georgia"  class="m-0 p-0">YV</h4> <span class="p-0 m-0 foundation">FOUNDATION</span></div></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link text-white" href="{% url 'yvfoundation:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link text-white" href="{% url 'yvfoundation:about'%}">About</a></li>
                <li class="nav-item"><a class="nav-link text-white" href="{% url 'yvfoundation:contact' %}">Contact us</a></li>


            </ul>
        </div>
    </div>
</nav>

<div id="overall" style="background-color:white; margin-top: 60px; width: 100%;height:100%;
      margin-bottom: 0; ">
{% block content %}

<div class="hero" id="hero" style="min-width:60vw;min-height:86vh;padding:0;margin:0">
    <div class="row">
        <div class="col-md-12">

            <img src="./static/images/stop.jpg" style="width:100%;height:100vh">
        </div>

    </div>



<!--    <div class="arrow-container " style="display:flex;justify-content:center;">-->
<!--    <a  href="#top-slogan" class="scroll-down-link scroll-down" style="font-size:5rem;font-weight:200" data-iconfont="ETmodules" data-icon>-->
<!--      </a>-->
<!--  </div>-->

</div>
<h4 class="slogan my-3 " id="top-slogan" style="width:100%;color:black"><span id="slogan-text" class="text-center" style="align-text:center;font-family: 'Libre Baskerville', serif;color:black">Changing the narrative starts with us.</span>
        </h4>
    <div class="row "  id="a1section" style="padding:0 30px;margin:0 auto;display:flex;justify-content:center" >
    <div class="w3-content w3-section col-md-4 col-sm-12"  style="padding:0;margin:auto 0;width:30%;height:350px">
  <img class="mySlides " src="./static/images/mandela.jpg"   style="width:100%;height:100%">
  <img class="mySlides" src="./static/images/END.jpg"   style="width:100%;height:100%">
  <img class="mySlides" src="./static/images/bw.jpg"  style="width:100%;height:100%">
        <img class="mySlides" src="./static/images/woman.jpg"  style="width:100%;height:100%">

</div>
          <div class="w3-content w3-section col-md-4 col-sm-12" style="margin:auto 0;padding:0;width:30%;height:350px" >
  <img class="mySlides1" src="./static/images/END.jpg"   style="width:100%;height:100%;">
  <img class="mySlides1" src="./static/images/bw.jpg"  style="width:100%;height:100%">
  <img class="mySlides1 " src="./static/images/woman.jpg"   style="width:100%;height:100%">
               <img class="mySlides1 " src="./static/images/mandela.jpg"   style="width:100%;height:100%">

</div>
          <div class="w3-content w3-section col-md-4 col-sm-12" style="margin:auto 0;padding:0;width:30%;height:350px">
  <img class="mySlides2" src="./static/images/bw.jpg"  style="width:100%;height:100%">
  <img class="mySlides2 " src="./static/images/woman.jpg"    style="width:100%;height:100%">
  <img class="mySlides2" src="./static/images/END.jpg"   style="width:100%;height:100%">
                <img class="mySlides2" src="./static/images/END.jpg"   style="width:100%;height:100%">

</div>

        </div>

        <main class="container huge" id="main" style="background-color:white">

    <div class="about row" id="asection" style="padding: 40px;">

        <div class="row">
        <div class="about-info  col-md-8 col-sm-12">
            <p class="text-center ">
                <b>YV Foundation</b> is a non-profit organization which was established in 2020 by a group of 4 young women aged
                “between” 23 to 34, who want to help with youth development and alleviating Gender Based Violence amongst the
                disadvantaged youth in South Africa. The organization addresses social issues such as unemployment and
                gender based violence.

            </p>
        </div>
        </div>




        <div class="row contact-details">
            <div class="contact-info col-md-6 col-sm-12 mt-2">
                <p>Ditsobotla, North West, South Africa<br>
                    073 3444 977<br>
                    yvfoundation1@gmail.com
                </p>
            </div>

        </div>
            <div class="col-md-4" style="align-items:center;display:flex;justify-content:space-around;flex-direction:row;margin: 0 auto">
<a href="{% url 'yvfoundation:home' %}" style="font-size:1.4rem;color:black;display:inline"><i class="fa-solid fa-house"></i></a>
              <a href="{% url 'yvfoundation:contact' %}" style="font-size:1.4rem;color:black;display:inline"> <i class="fa-solid fa-envelope"></i></a>
               <a href="{% url 'yvfoundation:contact' %}" style="font-size:1.6rem;color:blue;display:inline"><i class="fa-brands fa-facebook"></i></a>
    </div>
</div>

</main>






<div class="modalo p-0" style="width:100%;height:100%" >
    <div id="contents">
        <div class="closebar" style="display:flex;justify-content:flex-end">
        <button class="close-btn btn"><b>X</b></button>
        </div>
    <h4 id="feedback">Thanks.</h4>
    </div>


</div>



{% endblock %}



<!-- Footer-->
<footer class=" bg-dark mt-auto py-3 footer"  >
    <div class="row"><p class="text-center text-white">Copyright &copy; Created by Abigail Molusi</p>
    </div>
</footer>
     </div>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/main.js' %}"></script>
<script>

var myIndex = 0;
carousel();

function carousel() {
  var i;
  var x = document.getElementsByClassName("mySlides");
  var x1 = document.getElementsByClassName("mySlides1");
  var x2 = document.getElementsByClassName("mySlides2");
<!--  var x3 = document.getElementsByClassName("mySlides3");-->
for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
    x1[i].style.display = "none";
    x2[i].style.display = "none";
<!--    x3[i].style.display = "none";-->
 }
  myIndex++;
  if (myIndex > x.length) {myIndex = 1}
  x[myIndex-1].style.display = "block";
  x1[myIndex-1].style.display = "block";
  x2[myIndex-1].style.display = "block";
<!--  x3[myIndex-1].style.display = "block";-->
 setTimeout(carousel, 2000); // Change image every 2 seconds
}
</script>
</body>
</html>